---
- hosts: all
  become: yes
  vars:
  pre_tasks:
    - name: gather ec2 facts
      action: ec2_metadata_facts
      tags:
        - always

- hosts: base
  become: yes
  roles:
    - base
    - hardening

- hosts: vault
  become: yes
  vars:
    - vault_storage_dynamodb: true
  roles:
    - etc-environment
    - cfn-tools
    - ssh
    - vault