---

- name: Configure vault agent (base)
  template:
    src: base.hcl.j2
    dest: /etc/vault/conf.d/10-base.hcl
  tags:
  - configure

- name: Configure vault agent (telemetry)
  template:
    src: telemetry.hcl.j2
    dest: /etc/vault/conf.d/20-telemetry.hcl
  tags:
    - configure

- name: Configure vault agent (dynamodb storage backend)
  template:
    src: dynamodb.hcl.j2
    dest: /etc/vault/conf.d/30-dynamodb.hcl
  when: vault_storage_dynamodb
  tags:
  - configure

- name: Configure tcp kernel settings
  sysctl:
    name: net.ipv4.tcp_tw_reuse
    value: 1
    state: present
    reload: yes